SHOW DATABASES;
CREATE DATABASE newlec;

USE newlec;

-- 테이블 삭제
DROP TABLE NOTICE_VIEW;

-- 테이블 생성
CREATE TABLE NOTICE
( 
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITLE VARCHAR(100) NOT NULL,
	WRITER_ID VARCHAR(50) NOT NULL,
	CONTENT LONGTEXT,
	REGDATE DATETIME DEFAULT now() NOT NULL,
	HIT INT DEFAULT 0 NOT NULL,
	FILES VARCHAR(1000),
	PUB INT(1) DEFAULT 0 NOT NULL
);
