SELECT * FROM NOTICE;

SELECT COUNT(ID) COUNT FROM NOTICE;

INSERT INTO NOTICE (
	TITLE, WRITER_ID, CONTENT, files
) VALUE (
	'공지사항 테스트1', 'site-admin', '공지사항 테스트 입니다.', null
);

SET @ROWNUM:=0;
SELECT * FROM NOTICE ORDER BY REGDATE DESC;

-- 뷰 생성
CREATE VIEW NOTICE_VIEW
AS SELECT ROW_NUMBER() OVER(ORDER BY REGDATE DESC) AS NUM, N.* FROM NOTICE N;

SELECT ROW_NUMBER() OVER(ORDER BY REGDATE DESC) AS NUM, N.* FROM NOTICE N;

SELECT * FROM NOTICE_VIEW WHERE TITLE LIKE '%%' AND NUM BETWEEN 1 AND 10;

SELECT * FROM NOTICE WHERE TITLE LIKE '%%' AND ID BETWEEN 1 AND 10;
